CC = g++
CXXFLAGS = -g -Wall -Werror
LIBS = -litpp -lz -lpthread -lrt

all: consensus payouts

consensus: consensus.o
	$(CC) $(CXXFLAGS) -o consensus consensus.o $(LIBS)

consensus.o: consensus.cpp consensus.h
	$(CC) $(CXXFLAGS) -c consensus.cpp

payouts: payouts.o
	$(CXX) $(CXXFLAGS) -o payouts payouts.o

payouts.o: payouts.cpp payouts.h
	$(CXX) $(CXXFLAGS) -c payouts.cpp

clean:
	$(RM) payouts consensus payouts.o consensus.o
